analyzer:
  errors:
    dead_code: ignore
    todo: ignore
    unused_field: ignore
    unused_element: ignore
    unused_import: ignore
    unnecessary_this: ignore
    prefer_const_constructors: ignore
    use_build_context_synchronously: ignore
    no_leading_underscores_for_local_identifiers: ignore
    library_prefixes: ignore
    prefer_interpolation_to_compose_strings: ignore
    library_private_types_in_public_api: ignore
    unnecessary_null_comparison: ignore
linter:
  rules: